

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POSTS_FAILURE';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';
export const GET_ALL_USERS='GET_ALL_USERS';
export const CHANGE_CATEGORY='CHANGE_CATEGORY';
export const USER_SIGNUP='USER_SIGNUP';
export const FIND_USER='FIND_USER';
export const AUTHENTICATE_USER='AUTHENTICATE_USER';
export const UPDATE_USER='UPDATE_USER';
export const CLEAR_ERROR='CLEAR_ERROR';
export const CREATE_POST='CREATE_POST';
export const SINGLE_POST_DETAILS='SINGLE_POST_DETAILS';
export const UPDATE_CLAPS_COUNT='UPDATE_CLAPS_COUNT';
export const UPDATE_POST_DETAILS='UPDATE_POST_DETAILS';
export const DELETE_POST='DELETE_POST';
export const ADD_COMMENT='ADD_COMMENT';
export const GET_COMMENTS='GET_COMMENTS';
export const DELETE_COMMENT='DELETE_COMMENT';
export const EDIT_COMMENT='EDIT_COMMENT';
